const constants = {
  DROP_TOOL: 'DROP_TOOL',
  HOVER_TOOL: 'HOVER_TOOL',
  
  BUNDLE_READ: 'BUNDLE_READ',
  BUNDLE_EDITING: 'BUNDLE_EDITING',
  BUILD_NUMBER_INPUT: 'BUILD_NUMBER_INPUT',
  BUMP_BUNDLE: 'BUMP_BUNDLE',
  SET_BUILD_NUMBER: 'SET_BUILD_NUMBER'
}
export default constants
